### ISSUE TITLE
Add SQUAD Dataset

### ISSUE THREAD

**Issue by tshrjn** [PetrochukM/PyTorch-NLP#17]
One of the standard datasets used for machine comprehension tasks is [SQuaD](https://rajpurkar.github.io/SQuAD-explorer/). Thus, I suggest adding that to the `torchnlp.datasets package`

**Comment by hurricanelx** [comment]
#https://github.com/PetrochukM/PyTorch-NLP/pull/98

**Comment by PetrochukM** [comment]
This is done. Thanks @hurricanelx!
