### ISSUE TITLE
Can you help me with finding a way to map freebase MIDs to string in SimpleQuestions?

### ISSUE THREAD

**Issue by RamonYeung** [PetrochukM/PyTorch-NLP#40]
Thanks in advance.

**Comment by PetrochukM** [comment]
You need to download the Freebase knowledge graph and look at alias relations:
https://developers.google.com/freebase/

**Comment by PetrochukM** [comment]
Why are you working on this dataset?

This paper declared it solved: https://arxiv.org/abs/1804.08798

**Comment by RamonYeung** [comment]
Thanks for the pointers. I am having a hard time in preprocessing question answering dataset using Freebase as external knowledge source. By searching GitHub for any potential solution, I look into this repo and found general code for loading vary datasets.

This is why I am opening an issue to see whether I am lucky.
