### ISSUE TITLE
Consider not using lambdas as default arguments to enable pickling

### ISSUE THREAD

**Issue by benjamin-work** [PetrochukM/PyTorch-NLP#41]
## Problem description

Some classes have lambdas as default arguments (e.g. [here](https://github.com/PetrochukM/PyTorch-NLP/blob/aa23d5fa6733c724bec620ea5c94fe33e6ed6f78/torchnlp/text_encoders/static_tokenizer_encoder.py#L43)). This prevents these objects from being pickled.

## Steps to Reproduce the Problem

```
import pickle
from torchnlp.text_encoders import StaticTokenizerEncoder

encoder = StaticTokenizerEncoder(['hi', 'you'])
pickle.dumps(encoder) 

# raises error
PicklingError: Can't pickle <function StaticTokenizerEncoder.<lambda> at 0x7fb77c042b70>: attribute lookup StaticTokenizerEncoder.<lambda> on torchnlp.text_encoders.static_tokenizer_encoder failed
```

## Solution

Replace lambdas by actual functions.

**Comment by PetrochukM** [comment]
Until I get a freecycle to get to this, consider using ``dill`` a substitute for pickle that supports lambda functions.

**Comment by benjamin-work** [comment]
Yes, `dill` would work, but some libs resort to pickle (joblib). Maybe when I have time, I could make a PR for this but I wanted to make sure that this is something you would like to change.

**Comment by PetrochukM** [comment]
Thanks for your PR! Merged it with a couple updates.
