### ISSUE TITLE
Test on IMDB dataset is failing

### ISSUE THREAD

**Issue by pravarmahajan** [PetrochukM/PyTorch-NLP#43]
## Expected Behavior
The [test assertion](https://github.com/PetrochukM/PyTorch-NLP/blob/master/tests/datasets/test_imdb.py) checks if the first row of the Test Dataset of IMDB matches the given text and sentiment.

## Actual Behavior
The assertion fails, as the order of rows returned is not fixed. This is due to [glob.iglob](https://github.com/PetrochukM/PyTorch-NLP/blob/aa23d5fa6733c724bec620ea5c94fe33e6ed6f78/torchnlp/datasets/imdb.py#L65), which returns files [in arbitrary order](https://docs.python.org/3/library/glob.html).

## Steps to Reproduce the Problem
```
python -m pytest tests/datasets/test_imdb.py
```

or...

```
>>> from torchnlp.datasets import imdb
>>> train, test = imdb.imdb_dataset(train=True, test=True)
>>> print(test[0]['text'])
```

**Comment by PetrochukM** [comment]
Hi!

Update IMDB and IWSLT tests to be deterministic via this PR:
https://github.com/PetrochukM/PyTorch-NLP/pull/46

Thanks!
