### ISSUE TITLE
The SpacyEncoder tokenizes incorrectly

### ISSUE THREAD

**Issue by huhk-sysu** [PetrochukM/PyTorch-NLP#44]
## Expected Behavior

The SpacyEncoder should tokenize the sentence "This ain't funny." into ["This", "ai", "n't", "funny", "."].

## Actual Behavior

The SpacyEncoder tokenizes the sentence "This ain't funny." into ["This", "ain't", "funny."].

## Steps to Reproduce the Problem

1. Install latest PyTorch-NLP(0.3.5) and Spacy(2.0.11) 
2. 
```python
>>> from torchnlp.text_encoders import SpacyEncoder
>>> encoder = SpacyEncoder(["This ain't funny."])
>>> encoder.vocab
['<pad>', '<unk>', '</s>', '<s>', '<copy>', 'This', "ain't", 'funny.']
```
It behaves differently from [the example](https://pytorchnlp.readthedocs.io/en/latest/_modules/torchnlp/text_encoders/spacy_encoder.html#SpacyEncoder).

## Notes

I checked the source code and used Spacy to tokenize directly. 
```python
>>> import spacy
>>> from spacy.tokenizer import Tokenizer
>>> nlp = spacy.load('en_core_web_sm')
>>> doc = nlp(u"This ain't funny.")
>>> for token in doc:
...     print(token.text)
...
This
ai
n't
funny
.
>>> tokenizer = Tokenizer(nlp.vocab)
>>> doc = tokenizer(u"This ain't funny.")
>>> for token in doc:
...     print(token.text)
...
This
ain't
funny.
```

I tried running the same code on Spacy's website  and got the same result. It seems the tokenizer alone can't work properly.

I'm not sure whether there's something wrong with Spacy, or you are using it in a wrong way. Maybe I should open a issue on Spacy's repository?

**Comment by floscha** [comment]
While I don't fully understand the behavior of spaCy that you've explained in your notes, it's actually easy to achieve the expected tokenization with PyTorch-NLP by replacing the [lines 56-64](https://github.com/PetrochukM/PyTorch-NLP/blob/master/torchnlp/text_encoders/spacy_encoder.py#L56-L64) with the following code:
```python
try:
    tokenizer = spacy.load(language)
except OSError:
    raise ValueError(("Language '{0}' not found. Install using spaCy: `python -m spacy download {0}`").format(language))
```

However, the [StaticTokenizerEncoder](https://github.com/PetrochukM/PyTorch-NLP/blob/master/torchnlp/text_encoders/static_tokenizer_encoder.py) of PyTorch-NLP simply joins tokens together and puts a space characters between them for decoding (see the implementation [here](https://github.com/PetrochukM/PyTorch-NLP/blob/master/torchnlp/text_encoders/static_tokenizer_encoder.py#L75)).

This means that for the current encoder, the line `encoder.decode(encoder.encode("This ain't funny."))` returns `This ain't funny.`, while for the modified version `encoder.decode(encoder.encode("This ain't funny."))` results in `This ai n't funny .` (which is actually the output of the example that you've mentioned).

I guess @PetrochukM has to make a choice between an encoder that produces (arguably) better tokens or one that is reversible.

**Comment by PetrochukM** [comment]
Hi!

Update Spacy Encoder to work as expected in the documentation via this PR:
https://github.com/PetrochukM/PyTorch-NLP/pull/46

Spacy word tokenizer is required by future users, I invite them to submit a PR.

Thanks!
