### ISSUE TITLE
Example code is outdated, AWD now uses SplitCrossEntropyLoss rather than CrossEntropyLoss

### ISSUE THREAD

**Issue by liulu112601** [PetrochukM/PyTorch-NLP#47]
## Expected Behavior
CrossEntropyLoss
## Actual Behavior
SplitCrossEntropyLoss

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by PetrochukM** [comment]
Hi There!

The example code was put together 2 months back. Happy to have a PR to update the examples.

Thanks!
