### ISSUE TITLE
Ujson reliance doesn't permit successful install

### ISSUE THREAD

**Issue by dspoka** [PetrochukM/PyTorch-NLP#49]
## Expected Behavior
Having trouble installing this due to not being able to install ujson.
As I understand ujson is faster than json but has issues on different pythons. 
for example: https://github.com/jjjake/internetarchive/issues/14

## Steps to Reproduce the Problem
My system
```python
import sys
print(sys.version)
3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49)
[GCC 7.2.0]
```
1. pip3 install py pytorch-nlp

**Comment by AtmaHou** [comment]
I happened to solve it by installing the newest version of VS studio, but it re-occurs now. hoping for a solution for it.

**Comment by PetrochukM** [comment]
Sorry guys! Removed ``ujson`` from the code base since it's such a hassle. Please reinstall and it should be okay.
