### ISSUE TITLE
Dataset does not return tuple

### ISSUE THREAD

**Issue by zplizzi** [PetrochukM/PyTorch-NLP#50]
In the documentation for each dataset, it says `Returns: Tuple with the training tokens, dev tokens and test tokens in order if their respective boolean argument is true.`

However, when only a single split is selected, a tuple is not returned. The selected set is just returned directly.

Eg. running `len(penn_treebank_dataset(train=True))` should return `1`, but instead returns `929589`.

I understand that this was probably intended as a convenience measure, but a) the behavior and the docs should match, and b) generally it's better to have a function return consistently shaped data.

**Comment by PetrochukM** [comment]
Pushed an update here: https://github.com/PetrochukM/PyTorch-NLP/pull/56

The approach I used to fix this was to update the docs. I think A is a better approach for usability because it more closely follows Pythons spec.

Thanks for the detailed issue!
