### ISSUE TITLE
how to retrain the glove or other word vectorize models?

### ISSUE THREAD

**Issue by Blusea** [PetrochukM/PyTorch-NLP#52]
how to retrain the glove or other word vectorize algorithms?
Armed in search an sequence-based model for protain-protain binding prediction, it need to retain charactor vectorize model for amino acid sequence. In this repo, I just found the pretrained api.

**Comment by PetrochukM** [comment]
Hi!

If you are using pre-trained embeddings, you can initialize your model with the pre-trained embeddings and train; therefore, fine tuning the pre-trained embeddings or "retraining".
