### ISSUE TITLE
missing fine-grained option in smt dataset

### ISSUE THREAD

**Issue by mourga** [PetrochukM/PyTorch-NLP#54]
## PyTorch-NLP/torchnlp/datasets/smt.py

Although _"fine-grained"_ is an argument in the _smt_dataset()_ function, it is not used inside the function so this option does not work. A small modification is needed. Specifically, it should be given as an argument when the function _parse_tree()_ is called.

## Solution

lines 105 and 107 in smt.py should be changed (respectively) from:
                    examples.extend(parse_tree(line, subtrees=subtrees))
                    examples.append(parse_tree(line, subtrees=subtrees))
to:
                    examples.extend(parse_tree(line, subtrees=subtrees, **fine_grained=fine_grained**))
                    examples.append(parse_tree(line, subtrees=subtrees, **fine_grained=fine_grained**))

...and I believe the problem is fixed!

**Comment by PetrochukM** [comment]
Fixed and tested: https://github.com/PetrochukM/PyTorch-NLP/pull/56

Thanks for the detailed report!
