### ISSUE TITLE
Input batch size doesn't match hidden[0] batch size 

### ISSUE THREAD

**Issue by homelifes** [PetrochukM/PyTorch-NLP#62]
Hi. 
Hi. I am using an LSTMCell. However, I get this error:
`Input batch size 1 doesn't match hidden[0] batch size 512`

This is my testing code:
```
lstm = nn.LSTMCell(256,512)
weights = ['weight_hh']
weight_drop_gru = WeightDrop(lstm, weights, dropout=0.5)
input_ = torch.randn(1, 256)
hidden_state = torch.randn(1, 512)
weight_drop_gru(input_, hidden_state)
```
The input and hidden both have a batch_size of 1. Why does the GRUCell work but LSTMCell doesn't work?

**Comment by homelifes** [comment]
Never mind, fixed it.

**Comment by tmhm** [comment]
HI, @homelifes , How to fix it? I'm also getting this problem, Thanks.
