### ISSUE TITLE
Consider adding a batch_first option to follow more closely nn.RNN argument structure

### ISSUE THREAD

**Issue by jpilaul** [PetrochukM/PyTorch-NLP#63]
## Expected Behavior
model = nn.SRU(10, 10, batch_first=True) should work

## Actual Behavior
option not given

## Steps to Reproduce the Problem

1. model = nn.SRU(10, 10, batch_first=True)
2.
3.

**Comment by PetrochukM** [comment]
Hi!

Sorry for your issue. In the next version SRU will be removed, please use: https://github.com/taolei87/sru

Learn more: https://github.com/PetrochukM/PyTorch-NLP/pull/68

Thanks!
