### ISSUE TITLE
FastText memory requirements

### ISSUE THREAD

**Issue by zbyte64** [PetrochukM/PyTorch-NLP#65]
Attempted to instantiate `FastText` with 13 GB of RAM free, the system runs out of memory.

```
File "torchnlp\word_to_vector\pretrained_word_vectors.py", line 171, in cache
    self.vectors = torch.Tensor(vectors).view(-1, dim)
MemoryError
```

I've seen it mentioned elsewhere that 12 GB should be enough but it looks like we might have two copies of the vectors kicking around at one point.

**Comment by PetrochukM** [comment]
Fixed with https://github.com/PetrochukM/PyTorch-NLP/pull/68
