### ISSUE TITLE
LockedDropout - Doc Misleading

### ISSUE THREAD

**Issue by JiaqiLiu** [PetrochukM/PyTorch-NLP#71]
https://github.com/PetrochukM/PyTorch-NLP/blob/4c7a7ff41789ed93c0f15bb90fe7fb4400c8cf83/torchnlp/nn/lock_dropout.py#L55

Hi, in the code of LockedDropout, I found it confusing.
The doc/comment says: 
```
LockedDropout applies the same dropout mask to every time step.
x shape: [batch size, sequence length, rnn hidden size]
```

However, based on the implementation, I found that we are not applying the same dropout mask to every time step, but applying the same mask to every datapoint in a batch.

Looking forward to your reply. Thanks!

**Comment by PetrochukM** [comment]
Hi There!

Thanks for your feedback, please submit a PR with a better more clear doc.

Thanks!

**Comment by JiaqiLiu** [comment]
yes done!
