### ISSUE TITLE
bleu metric doesn't seem to work properly

### ISSUE THREAD

**Issue by HadiZayer** [PetrochukM/PyTorch-NLP#78]
I tried to test the get_moses_multi_bleu metric and it doesn't seem to work properly.
I ran the following:
```
x = ['abc']
y = ['abc']
print(get_moses_multi_bleu(x,y))
```
and it prints `0.0` instead of `1`

Edit: I believe the reason is that because the sentence is too short for 2-gram, 3-gram, etc... So there should be a warning message in that case

**Comment by PetrochukM** [comment]
Please submit this issue to https://raw.githubusercontent.com/moses-smt/mosesdecoder/master/scripts/generic/multi-bleu.perl

PyTorch-NLP relies on the official BLEU metric; therefore, by definition, it computes BLEU correctly.
