### ISSUE TITLE
There is bpemb, but there is no Byte-Pair Encoding.

### ISSUE THREAD

**Issue by illcat** [PetrochukM/PyTorch-NLP#81]
## Steps to Reproduce the Problem

1.
2.
3.

**Comment by PetrochukM** [comment]
Please provide more information... What do you mean there is "no Byte-Pair encoding"?

**Comment by illcat** [comment]
Encoder for bpemb.

**Comment by illcat** [comment]
> Please provide more information... What do you mean there is "no Byte-Pair encoding"?

Encoder for bpemb.

**Comment by PetrochukM** [comment]
Sorry. Please use full sentences instead of phrases when submitting issues. I won't be taking the time to figure out your cryptic references.
