### ISSUE TITLE
Tempfile PermissionError after bleu demo  on windows

### ISSUE THREAD

**Issue by laohur** [PetrochukM/PyTorch-NLP#83]
## Expected Behavior
ok

## Actual Behavior
Traceback (most recent call last):
  File "D:/doc/nlp/ContextTransformer/demo.py", line 7, in <module>
    bleu=get_moses_multi_bleu(hypotheses, references, lowercase=True)  # RETURNS: 47.9
  File "C:\ProgramData\Anaconda3\lib\site-packages\torchnlp\metrics\bleu.py", line 86, in get_moses_multi_bleu
    with open(hypothesis_file.name, "r") as read_pred:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\XUECHA~1\\AppData\\Local\\Temp\\tmpluhikfae'

## Steps to Reproduce the Problem
from torchnlp.metrics import get_moses_multi_bleu

hypotheses = ["The brown fox jumps over the dog 笑"]
references = ["The quick brown fox jumps over the lazy dog 笑"]

 Compute BLEU score with the official BLEU perl script
bleu=get_moses_multi_bleu(hypotheses, references, lowercase=True)  # RETURNS: 47.9
print(bleu)

**Comment by PetrochukM** [comment]
This is a system issue and a Python issue. Please do your own research on using `tempfile.NamedTemporaryFile` on windows. This is a python native module.

**Comment by laohur** [comment]
> 
> 
> This is a system issue and a Python issue. Please do your own research on using `tempfile.NamedTemporaryFile` on windows. This is a python native module.

yes, it is. But it is not elegant on windows. How to slove it ,or replace it ?
