### ISSUE TITLE
The link to the penn treebank dataset seems to be broken.

### ISSUE THREAD

**Issue by whwang299** [PetrochukM/PyTorch-NLP#86]
Hi Michael Petrochuk

Just to inform you that the link to the penn treebank dataset (https://github.com/PetrochukM/PyTorch-NLP/blob/66290b5a7a0a7fddbd0f93e3bd735491b8614caa/torchnlp/datasets/penn_treebank.py#L31)
seems to be broken.

Thanks for your neat work!

**Comment by seanhung21** [comment]
I'll work on this.
